resolver: lts-11.21

# due to functor-infix
allow-newer: true

packages:
  - '.'
#  - '../grin/grin'
  - location:
      git: https://github.com/grin-tech/grin
      commit: 663014f63b50aca02ed6d9303249a23faa879b1f
    subdirs:
      - grin
    extra-dep: true

extra-deps:
  - monad-gen-0.3.0.1
  - llvm-hs-pretty-0.2.0.0
  - functor-infix-0.0.5

flags:
  llvm-hs:
    shared-llvm: true

build:
  test-arguments:
    additional-args:
      - "--seed=11010"
